name: 'colcon_test'
description: 'Import some repositories and their versions from a yaml file'

inputs:

  colcon_test_args:
    description: 'args to pass to colcon test command (use ctest_args to set ctest arguments)'
    required: false
    default: ''

  colcon_test_args_default:
    description: 'Default args to pass to colcon test command (use ctest_args to set ctest arguments)'
    required: false
    default: '--event-handlers=console_direct+ --return-code-on-test-failure'

  ctest_args:
    description: 'args to pass to colcon test command'
    required: false
    default: ''

  ctest_args_default:
    description: 'Default args to pass to colcon test command'
    required: false
    default: '--timeout 60'

  workspace:
    description: 'Workspace where built is done'
    required: false
    default: './'

  workspace_dependencies:
    description: 'Workspace to source where dependencies are'
    required: false
    default: ''

runs:
  using: composite
  steps:

    - name: Run in ubuntu
      uses: jparisu/eProsima-CI/ubuntu/colcon_build@feature/windows-support
      if: runner.os == 'Linux'
      with:
        colcon_test_args: ${{ inputs.colcon_test_args }}
        colcon_test_args_default: ${{ inputs.colcon_test_args_default }}
        ctest_args: ${{ inputs.ctest_args }}
        ctest_args_default: ${{ inputs.ctest_args_default }}
        workspace: ${{ inputs.workspace }}
        workspace_dependencies: ${{ inputs.workspace_dependencies }}

    - name: Run in windows
      uses: jparisu/eProsima-CI/windows/colcon_build@feature/windows-support
      if: runner.os == 'Windows'
      with:
        colcon_test_args: ${{ inputs.colcon_test_args }}
        colcon_test_args_default: ${{ inputs.colcon_test_args_default }}
        ctest_args: ${{ inputs.ctest_args }}
        ctest_args_default: ${{ inputs.ctest_args_default }}
        workspace: ${{ inputs.workspace }}
        workspace_dependencies: ${{ inputs.workspace_dependencies }}
