name: 'install_fastdds_dependencies'
description: 'Install Fast DDS dependencies in ubuntu'

inputs:
  cmake_build_type:
    description: 'Unused variable'
    required: false

runs:
  using: composite
  steps:

    - name: Install vcs tools
      uses: eProsima/eProsima-CI/ubuntu/install_python_packages@v0.2.0
      with:
        packages: 'vcstool setuptools'

    - name: Install colcon
      uses: eProsima/eProsima-CI/ubuntu/install_colcon@v0.2.0

    - name: Install GTest
      uses: eProsima/eProsima-CI/ubuntu/install_gtest@v0.2.0

    - name: Install asio
      uses: eProsima/eProsima-CI/ubuntu/install_asio@v0.2.0

    - name: Install Tiny XML
      uses: eProsima/eProsima-CI/ubuntu/install_tinyxml@v0.2.0

    - name: Install Open SSL
      uses: eProsima/eProsima-CI/ubuntu/install_openssl@v0.2.0
