name: 'install_fastdds_dependencies'
description: 'Install Fast DDS dependencies in ubuntu'

inputs:
  cmake_build_type:
    description: 'Unused variable'
    required: false

runs:
  using: composite
  steps:

    - name: Install vcs tools
      uses: eProsima/eProsima-CI/ubuntu/install_python_packages@feature/shared_resources
      with:
        packages: 'vcstool setuptools'

    - name: Install colcon
      uses: eProsima/eProsima-CI/ubuntu/install_colcon@feature/shared_resources

    - name: Install GTest
      uses: eProsima/eProsima-CI/ubuntu/install_gtest@feature/shared_resources

    - name: Install asio
      uses: eProsima/eProsima-CI/ubuntu/install_asio@feature/shared_resources

    - name: Install Tiny XML
      uses: eProsima/eProsima-CI/ubuntu/install_tinyxml@feature/shared_resources

    - name: Install Open SSL
      uses: eProsima/eProsima-CI/ubuntu/install_openssl@feature/shared_resources
