name: 'install_fastdds_dependencies'
description: 'Install Fast DDS dependencies in ubuntu'

inputs:
  # Set CMake version inputs
  cmakeVersion:
    required: false
    description: |
      Optional CMake version, expressed with the semantic version syntax,
      e.g. '~3.25.0' for the most recent 3.25.x, `Ë†3.25.0` for the most
      recent 3.x version, or a specific version `3.25.2'. Or `latest` or
      `latestrc` for the latest stable or release candidate version. If not
      specified the `latest` is installed.
    default: '3.22.x'

  ninjaVersion:
    required: false
    description: |
      Optional Ninja version, same syntax as `cmakeVersion` input.
      If not specified, `latest` is installed"

runs:
  using: composite
  steps:

    - name: Set CMake version
      uses: eProsima/eProsima-CI/external/get-cmake@feature/artifact-build
      with:
        cmakeVersion: ${{ inputs.cmakeVersion }}
        ninjaVersion: ${{ inputs.ninjaVersion }}

    - name: Install vcs tools
      uses: eProsima/eProsima-CI/ubuntu/install_python_packages@feature/artifact-build
      with:
        packages: 'vcstool setuptools'

    - name: Install colcon
      uses: eProsima/eProsima-CI/ubuntu/install_colcon@feature/artifact-build

    - name: Install GTest
      uses: eProsima/eProsima-CI/ubuntu/install_gtest@feature/artifact-build

    - name: Install asio
      uses: eProsima/eProsima-CI/ubuntu/install_asio@feature/artifact-build

    - name: Install Tiny XML
      uses: eProsima/eProsima-CI/ubuntu/install_tinyxml@feature/artifact-build

    - name: Install Open SSL
      uses: eProsima/eProsima-CI/ubuntu/install_openssl@feature/artifact-build
