name: 'install_uncrustify'
description: 'Install uncrustify project'

inputs:
  uncrustify_version:
    description: 'Specify a branch to download'
    required: false
    default: '0.72.0+dfsg1-2'

runs:
  using: composite
  steps:

    - name: Install uncrustify

      run: |
        echo "::group::Install Uncrustify ubuntu 22.04"
        sudo apt install uncrustify=${{ inputs.uncrustify_version }}
        echo "::endgroup::"

      shell: bash
