name: install_uncrustify

runs:
  using: composite
  steps:

    - name: Install uncrustify
      uses: eProsima/eProsima-CI/ubuntu/install_apt_packages@hotfix/upgrade-setuptools
      with:
        packages: uncrustify
