name: 'get_configurations_from_repo'
description: 'TODO'

inputs:

  source_repository_branch:
    description: 'TODO'
    required: true

  source_repository:
    description: 'TODO'
    required: false
    default: '$GITHUB_REPOSITORY'

  colcon_meta_file_result:
    description: 'TODO'
    required: false
    default: 'colcon.meta'

  colcon_meta_file_path:
    description: 'TODO'
    required: false
    default: 'colcon.meta'

  repos_file_result:
    description: 'TODO'
    required: false
    default: 'dependencies.repos'

  repos_file_path:
    description: 'TODO'
    required: false
    default: 'dependencies.repos'

runs:
  using: composite
  steps:

    - name: Get colcon.meta file
      uses: jparisu/eProsima-CI/ubuntu/get_file_from_repo@main
      with:
        source_repository_branch: ${{ inputs.source_repository_branch }}
        source_repository: ${{ inputs.source_repository }}
        file_name: ${{ inputs.colcon_meta_file_path }}
        file_result: ${{ inputs.colcon_meta_file_result }}

    - name: Get dependencies.repos file
      uses: jparisu/eProsima-CI/ubuntu/get_file_from_repo@main
      with:
        source_repository_branch: ${{ inputs.source_repository_branch }}
        source_repository: ${{ inputs.source_repository }}
        file_name: ${{ inputs.repos_file_path }}
        file_result: ${{ inputs.repos_file_result }}
