name: get_file_from_repo
description: Download a file from a github repository

inputs:

  source_repository_branch:
    description: Branch or reference of the repository to download files
    required: false
    default: main

  source_repository:
    description: Github repository to download files in format <user/repo_name>
    required: false
    default: ''

  file_name:
    description: Colcon meta to set cmake options to packages
    required: true

  file_result:
    description: Name of the result file
    required: false
    default: ''

runs:
  using: composite
  steps:

    - name: Get file
      shell: bash
      run: |

        echo "::group::Get file using wget"

        if [[ -z "${{ inputs.file_result }}" ]]; then
          export FILE_RESULT_="${{ inputs.file_name }}"
        else
          export FILE_RESULT_="${{ inputs.file_result }}"
        fi

        echo "Calling wget with url: https://raw.githubusercontent.com/${{ inputs.source_repository }}/${{ inputs.source_repository_branch }}/${{ inputs.file_name }}"

        wget \
          -O ${FILE_RESULT_} \
          https://raw.githubusercontent.com/${{ inputs.source_repository }}/${{ inputs.source_repository_branch }}/${{ inputs.file_name }}

        echo "File downloaded:"
        cat ${{ inputs.file_result }}

        echo "::endgroup::"
