name: 'install_python_packages'
description: 'Install generic and required python packages with pip'

inputs:
  custom_packages:
    description: 'Custom packages to install using pip'
    required: false
    default: 'vcstool setuptools'

runs:
  using: composite
  steps:

    - name: install_python_packages

      run: |
        echo "::group::Install Python packages"
        sudo pip3 install -U \
          ${{ inputs.custom_packages }}
        echo "::endgroup::"

      shell: bash
