name: 'install_python_packages'
description: 'Install generic and required python packages with pip'

inputs:

  packages:
    description: 'Custom packages to install using pip'
    required: false
    default: ''

  upgrade:
    description: 'Upgrade already installed packages'
    required: false
    default: false

  requirements_file_name:
    description: 'If set, the file name of a requirements.txt file'
    required: false
    default: ''

  path:
    description: 'Path to the installation folder'
    required: false
    default: ''

runs:
  using: composite
  steps:

    - name: install_python_packages
      run: |

        echo "::group::Install Python packages"

        # Set upgrade flag
        if [ "${{ inputs.upgrade }}" = "true" ]; then
          export UPGRADE_FLAG="--upgrade"
        else
          export UPGRADE_FLAG=""
        fi

        # Check if installation path is set
        if [[ ! -z "${{ inputs.path }}" ]] ; then
          export INSTALL_PATH="--target ${{ inputs.path }}"
        else
          export INSTALL_PATH=""
        fi

        # Install python packages if any
        if [[ ! -z "${{ inputs.packages }}" ]] ; then
          pip3 install --user ${UPGRADE_FLAG} ${INSTALL_PATH} \
            ${{ inputs.packages }}
        fi

        # Install requirements file if any
        if [[ ! -z "${{ inputs.requirements_file_name }}" ]] ; then
          pip3 install --user ${UPGRADE_FLAG} ${INSTALL_PATH} \
            -r ${{ inputs.requirements_file_name }}
        fi

        echo "::endgroup::"

      shell: bash
