name: 'install_python_packages'
description: 'Install generic and required python packages with pip'

inputs:

  packages:
    description: 'Custom packages to install using pip'
    required: false
    default: ''

  requirements_file_name:
    description: 'If set, the file name of a requirements.txt file'
    required: false
    default: ''


runs:
  using: composite
  steps:

    - name: install_python_packages
      run: |

        echo "::group::Install Python packages"

        # Install python packages if any
        if [[ ! -z "${{ inputs.packages }}" ]] ; then
          sudo pip3 install -U \
            ${{ inputs.packages }}
        fi

        # Install requirements file if any
        if [[ ! -z "${{ inputs.requirements_file_name }}" ]] ; then
          sudo pip3 install -U \
            -r ${{ inputs.requirements_file_name }}
        fi


        echo "::endgroup::"

      shell: bash
