name: install_uncrustify

inputs:

  uncrustify_version:
    description: 'Specify a branch to download'
    required: false
    default: 'uncrustify-0.72.0'

runs:
  using: composite
  steps:

    - name: Install uncrustify
      shell: bash
      run: |

        echo "::group::Install Uncrustify ubuntu 20.04"

        git clone https://github.com/uncrustify/uncrustify.git \
          --branch ${{ inputs.uncrustify_version }} \
          --single-branch uncrustify
        mkdir -p uncrustify/build
        cd uncrustify/build
        cmake ..
        sudo cmake --build . --target install
        cd ../..
        sudo rm -rf uncrustify

        echo "::endgroup::"
