name: 'setup_python_venv'
description: 'Setup a Python virtual environment and add it to the PATH'

inputs:

  path:
    description: 'Path to virtual environment'
    required: false
    default: '.venv'

  activate_global:
    description: 'Activate the virtual environment globally'
    required: false
    default: true

runs:
  using: composite
  steps:

    - name: 'setup_python_venv'
      shell: pwsh
      run: |
        "::group::Setup Python virtual environment"

        python -m venv ${{ inputs.path }}
        .\.venv\Scripts\Activate.ps1

        if (${{ inputs.path }} -eq "true") {
          $env:PATH | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        }

        "::endgroup::"
