name: 'setup_python_venv'
description: 'Setup a Python virtual environment and add it to the PATH'

runs:
  using: composite
  steps:

    - name: 'setup_python_venv'
      shell: pwsh
      run: |
        "::group::Setup Python virtual environment"

        python -m venv .venv
        .\.venv\Scripts\Activate.ps1
        $env:PATH | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

        "::endgroup::"
