name: 'vcs_import'
description: 'Import some repositories and their versions from a yaml file'

inputs:

  vcs_repos_file:
    description: '.repos file to import repositories'
    required: true

  destination_workspace:
    description: 'Workspace to source where dependencies are'
    required: false
    default: './'

runs:
  using: composite
  steps:

    - name: vcs_import
      run: |

        echo "::group::Import repositories from ${{ inputs.vcs_repos_file }}"

        echo "Downloading following dependencies:"
        cat ${{ inputs.vcs_repos_file }}

        mkdir -p ${{ inputs.destination_workspace }}

        vcs import ${{ inputs.destination_workspace }} < ${{ inputs.vcs_repos_file }}

        echo "::endgroup::"

      shell: bash
