name: 'install_yamlcpp'
description: 'Install yaml cpp'

runs:
  using: composite
  steps:

    - name: Install in ubuntu
      uses: jparisu/eProsima-CI/ubuntu/install_apt_packages@feature/windows-support
      with:
        custom_packages: libyaml-cpp-dev
