name: fetch_fastdds_manual
description: Download Fast DDS and its eProsima dependencies setting the specific version of each repository

inputs:

  foonathan_memory_vendor_branch:
    description: Branch, tag or commit of eProsima/foonathan_memory_vendor repository. Check available branches in https://github.com/eProsima/foonathan_memory_vendor.
    required: false
    default: master

  fastcdr_branch:
    description: Branch, tag or commit of eProsima/Fast-CDR repository. Check available branches in https://github.com/eProsima/Fast-CDR.
    required: false
    default: master

  fastdds_branch:
    description: Branch, tag or commit of eProsima/Fast-DDS repository. Check available branches in https://github.com/eProsima/Fast-DDS.
    required: false
    default: master

  destination_workspace:
    description: 'Workspace where the repositories are downloaded'
    required: false
    default: '${{ github.workspace }}'

runs:
  using: composite
  steps:

    - name: fetch_fastdds_manual
      shell: pwsh
      run: |

        "::group::Manually clone Fast DDS repositories"

        Write-Host 'Downloading following dependencies:'
        Write-Host '  - Foonathan Memory Vendor: ${{ inputs.foonathan_memory_vendor_branch }}'
        Write-Host '  - Fast CDR: ${{ inputs.fastcdr_branch }}'
        Write-Host '  - Fast DDS: ${{ inputs.fastdds_branch }}'

        New-Item -ItemType Directory -Force -Path ${{ inputs.destination_workspace }}
        Set-Location -Path ${{ inputs.destination_workspace }}

        git clone --branch ${{ inputs.foonathan_memory_vendor_branch }} https://github.com/eProsima/foonathan_memory_vendor.git
        git clone --branch ${{ inputs.fastcdr_branch }} https://github.com/eProsima/Fast-CDR.git
        git clone --branch ${{ inputs.fastdds_branch }} https://github.com/eProsima/Fast-DDS.git

        "::endgroup::"
