name: 'download-artifact'
description: 'https://github.com/actions/upload-artifact/blob/main/action.yml'

inputs:

  name:
    description: 'Artifact name'
    required: false

  path:
    description: 'Destination path'
    required: false

runs:
  using: composite
  steps:

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
