name: 'colcon_build_test_flaky'
description: 'Compile code with colcon, and run colcon test.'

inputs:

  packages_names:
    description: 'Name of the colcon packages to build and test'
    required: true

  colcon_meta_file:
    description: 'colcon.meta file to set cmake options. If empty, it does not use any file'
    required: false
    default: ''

  cmake_args:
    description: 'Cmake arguments'
    required: false
    default: '-DBUILD_TESTS=ON'

  ctest_args:
    description: 'cTest arguments'
    required: false
    default: ''

  workspace:
    description: 'Workspace to build'
    required: false
    default: '${{ github.workspace }}'

  workspace_dependencies:
    description: 'Workspace to source where dependencies are'
    required: false
    default: ''

runs:
  using: composite
  steps:

    - name: Build
      uses: eProsima/eProsima-CI/multiplatform/colcon_build@v0.6.0
      with:
        colcon_meta_file: ${{ inputs.colcon_meta_file }}
        colcon_build_args: '--packages-up-to ${{ inputs.packages_names }}'
        cmake_args: ' ${{ inputs.cmake_args }}'
        workspace: ${{ inputs.workspace }}
        workspace_dependencies: ${{ inputs.workspace_dependencies }}

    - name: Test
      uses: eProsima/eProsima-CI/multiplatform/colcon_test@v0.6.0
      with:
        workspace: ${{ inputs.workspace }}
        colcon_test_args: '--packages-select ${{ inputs.packages_names }} ${{ inputs.colcon_test_args }}'
        ctest_args: ' --label-regex "xfail" ${{ inputs.ctest_args }}'
