name: 'install_colcon'
description: 'Install colcon'

runs:
  using: composite
  steps:

    - name: Install colcon
      uses: eProsima/eProsima-CI/ubuntu/install_python_packages@main
      with:
        packages: vcstool setuptools colcon-common-extensions colcon-mixin
