name: 'install_colcon'
description: 'Install colcon'

runs:
  using: composite
  steps:

    - name: install colcon
      uses: eProsima/eProsima-CI/ubuntu/install_python_packages@v0.2.0
      with:
        packages: 'setuptools==58.3.0 colcon-common-extensions colcon-mixin'
        upgrade: true
