name: 'install_coverage_requirements'
description: 'Install coverage requirements for cpp'

runs:
  using: composite
  steps:

    - name: Install docs requirements with apt
      uses: jparisu/eProsima-CI/ubuntu/install_apt_packages@feature/windows-support
      with:
        custom_packages: \
          lcov

    - name: Install docs requirements with pip
      uses: jparisu/eProsima-CI/ubuntu/install_python_packages@feature/windows-support
      with:
        custom_packages: \
          gcovr==5.0
