name: 'install_ccache'
description: 'Install last version of ccache'

runs:
  using: composite
  steps:

    - name: install_ccache
      shell: pwsh
      run: |

        "::group::Install CCache"

        ####### Download and extract ccache
        $erroractionpreference = "stop"

        $tag = (Invoke-WebRequest -Uri "https://api.github.com/repos/ccache/ccache/releases" -UseBasicParsing | ConvertFrom-Json)[0].tag_name
        $name = (Invoke-WebRequest -Uri "https://api.github.com/repos/ccache/ccache/releases" -UseBasicParsing | ConvertFrom-Json)[0].name
        $filename = "ccache-$name-windows-x86_64"
        $tarball = "$filename.zip"

        $outdir = $pwd.Path
        $outdir = "$outdir\.ccache"
        mkdir $outdir
        $ProgressPreference = 'SilentlyContinue'
        Invoke-WebRequest -Uri "https://github.com/ccache/ccache/releases/download/$tag/$tarball" -OutFile "$outdir\$tarball"

        Add-Type -AssemblyName System.IO.Compression.FileSystem
        [System.IO.Compression.ZipFile]::ExtractToDirectory("$outdir\$tarball", "$outdir")
        Move-Item -Path "$outdir\$filename" -Destination "$outdir\ccache"

        ####### Configuring ccache
        $ccache_dir = "$outdir\ccache"
        echo "$ccache_dir" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        Set-Item -Force -Path "env:PATH" -Value "$ccache_dir;$env:PATH"
        ccache --version

        "::endgroup::"
