# TODO

name: 'sphinx_docs'
description: TODO

inputs:

  docs_subpackage_name:
    description: 'Name of colcon subpackage that contains the sphinx documentation'
    required: false
    default: ''

  specific_cmake_args:
    description: 'Arguments for colcon build'
    required: false
    default: '-DBUILD_DOCS=ON -DBUILD_DOCS_TESTS=ON'

runs:
  using: composite
  steps:

    - name: Sync repository
      uses: actions/checkout@v3
      with:
        path: src

    - name: Install docs dependencies
      uses: eProsima/eProsima-CI/ubuntu/install_documentation_requirements@feature/annapurna-workflows

    - name: Install Colcon
      uses: eProsima/eProsima-CI/ubuntu/install_colcon@feature/annapurna-workflows

    - name: Download cmake_utils artifact
      uses: eProsima/eProsima-CI/multiplatform/download_dependency@feature/annapurna-workflows
      with:
        artifact_name: built_dev_utils_ubuntu-22.04_Release_nightly
        workflow_source: build_dev_utils.yml
        workflow_source_repository: jparisu/eProsima-CI
        target_workspace: '${{ github.workspace }}/install'

    - name: Build documentation with colcon
      uses: eProsima/eProsima-CI/multiplatform/colcon_build@feature/annapurna-workflows
      with:
        colcon_build_args: '--packages-select ${{ inputs.docs_subpackage_name }}'
        cmake_args: '${{ inputs.specific_cmake_args }}'
        workspace_dependencies: '${{ github.workspace }}/install'

    - name: Run colcon test of documentation
      uses: eProsima/eProsima-CI/multiplatform/colcon_test@feature/annapurna-workflows
      with:
        colcon_test_args: --packages-select ${{ inputs.docs_subpackage_name }}

    - name: Upload documentation
      uses: actions/upload-artifact@v3
      with:
        name: Documentation HTML ${{ inputs.docs_subpackage_name }}
        path: install/${{ inputs.docs_subpackage_name }}/docs/${{ inputs.docs_subpackage_name }}/sphinx/html/
