# Execute Uncrustify job from the same repo that calls this action.
#
# Action steps:
# - Checkout repository and fetch unshallow to be able to compare
# - Install packages required, including manually installation of uncrustify and ament_uncrustify
# - Get the file names of those files that has changed between base and head branch
# - Execute uncrustify over those files (only c++ ones) and store in ${result_filename} file.

name: 'uncrustify'
description: 'Uncrustify action to check C++ linter over modified files.'

inputs:

  result_filename:
    description: 'File name to store the changes'
    required: false
    default: uncrustify_results.xml

  # This argument is passed to a grep function to make the filter, so use grep arguments
  file_extensions_grep_args:
    description: 'Extensions of the files to check as C++, as grep filter arguments.'
    required: false
    default: "-e '\\.h' -e '\\.hpp' -e '\\.cpp' -e '\\.ipp'"

  # NOTE: there is no uncrustify version because it could not be set the same default for both ubuntu 20 and 22

runs:
  using: composite
  steps:

    - name: Sync repository
      uses: actions/checkout@v3
      with:
        path: src

    - name: Fetch all branches and tags
      run: |
        echo "::group::Fetch all branches"
        cd src
        git fetch --prune --unshallow
        echo "::endgroup::"
      shell: bash

    - name: Install apt packages
      uses: eProsima/eProsima-CI/ubuntu/install_apt_packages@tools/tmp

    - name: Install Python packages
      uses: eProsima/eProsima-CI/ubuntu/install_python_packages@tools/tmp
      with:
        custom_packages: "colcon-common-extensions \ colcon-mixin"

    - name: Install uncrustify
      uses: eProsima/eProsima-CI/ubuntu/install_uncrustify@tools/tmp

    # TODO: Change to main branch when PR is merged to allow c++ check over other files different than cpp hpp
    # (required for .ipp files)
    - name: Clone and build ament_lint
      run: |
        echo "::group::Build ament_lint"
        git clone --branch feature/fix-language-set https://github.com/jparisu/ament_lint.git src/ament_lint
        colcon build --packages-up-to ament_uncrustify
        echo "::endgroup::"
      shell: bash

    - name: Fetch uncrustify config file
      run: |
        curl \
          -l https://raw.githubusercontent.com/eProsima/cpp-style/master/uncrustify.cfg \
          -o uncrustify.cfg
      shell: bash

    - name: Get Git difference
      id: GetGitDifference
      uses: eProsima/eProsima-CI/ubuntu/get_git_diff_files@tools/tmp
      with:
        result_env_var:
          MODIFIED_FILES
        head_ref:
          origin/${GITHUB_HEAD_REF}
        base_ref:
          origin/${GITHUB_BASE_REF}
        grep_args:
          ${{ inputs.file_extensions_grep_args }}
        workspace:
          src

    - name: Check difference is not empty
      run: |
        cd src
        if [[ -z "${MODIFIED_FILES}" ]]
        then
          touch __empty.hpp
          echo "MODIFIED_FILES=__empty.hpp" >> $GITHUB_ENV
        fi
        echo "Files to check: ${MODIFIED_FILES}"
      shell: bash

    - name: Check style
      run: |
        source install/local_setup.bash
        cd src

        echo "################################################################################################"
        echo "###################################### UNCRUSTIFY RESULT #######################################"

        ament_uncrustify \
          -c ../uncrustify.cfg \
          --language CPP \
          --xunit-file ../${{ inputs.result_filename }} \
          ${MODIFIED_FILES}

        echo "################################# UNCRUSTIFY CHECK SUCCESSFUL ##################################"
        echo "################################################################################################"

      shell: bash
