name: 'merge_yaml_metas'
description: Merge given metas into a single meta file. Required because colcon in Windows does not merge them automatically.

inputs:

  metas:
    description: 'Array of yaml metas to merge'
    required: true
  path:
    description: 'Path to save the merged meta file'
    required: true

runs:
  using: composite
  steps:

    - name: Merge yaml metas
      shell: pwsh
      run: |
        $combined_content = @()

        foreach ($meta in ${{ inputs.metas }})
        {
          if ($meta -eq ${{ inputs.metas }}[0])
          {
            # Read the content of the first meta file
            $meta_content = Get-Content -Path $meta
          }
          else
          {
            # Read the content of the meta file, starting from line 2
            # (skipping "name" line [1], but keeping cmake project name line [2] and "cmake-args" line [3])
            $meta_content = Get-Content -Path $meta | Select-Object -Skip 1
          }
          $combined_content += $meta_content
        }

        # Write the combined content to the output meta file
        $combined_content | Out-File -FilePath ${{ inputs.path }} -Encoding UTF8

        # Display the combined content
        echo "Merged .meta content"
        echo $combined_content
