name: 'vcs_import'
description: 'Import required repositories and their versions from a .repos file'

inputs:

  vcs_repos_file:
    description: '.repos file to import repositories'
    required: true

  destination_workspace:
    description: 'Workspace where the repositories are downloaded'
    required: false
    default: '${{ github.workspace }}'

  skip_existing:
    description: 'Skip existing repositories'
    required: false
    default: 'false'

runs:
  using: composite
  steps:

    - name: vcs_import
      shell: pwsh
      run: |

        "::group::Import repositories from ${{ inputs.vcs_repos_file }}"

        New-Item -ItemType Directory -Path ${{ inputs.destination_workspace }} -Force

        $SKIP_EXISTING = $null
        if ("${{ inputs.skip_existing }}" -eq "true") {
          $SKIP_EXISTING = "--skip_existing"
        }

        vcs import $SKIP_EXISTING ${{ inputs.destination_workspace }} --input ${{ inputs.vcs_repos_file }}

        "::endgroup::"
