name: 'install_fast_dependencies'
description: 'Install Open SSl package'

runs:
  using: composite
  steps:

    - name: Install vcs tools
      uses: jparisu/eProsima-CI/ubuntu/install_python_packages@main

    - name: Install colcon
      uses: jparisu/eProsima-CI/ubuntu/install_colcon@main

    - name: Install in ubuntu
      uses: jparisu/eProsima-CI/ubuntu/install_apt_packages@main
      with:
        custom_packages: libasio-dev libtinyxml2-dev libssl-dev
