name: 'colcon_test'
description: 'Execute colcon test command with arguments given'

inputs:

  colcon_test_args:
    description: 'args to pass to colcon test command (use ctest_args to set ctest arguments)'
    required: false
    default: ''

  colcon_test_args_default:
    description: 'Default args to pass to colcon test command (use ctest_args to set ctest arguments)'
    required: false
    default: '--event-handlers=console_direct+ --return-code-on-test-failure'

  ctest_args:
    description: 'args to pass to colcon test command'
    required: false
    default: ''

  ctest_args_default:
    description: 'Default args to pass to colcon test command'
    required: false
    default: '--timeout 60'

  workspace:
    description: 'Workspace where built is done'
    required: false
    default: '${{ github.workspace }}'

  workspace_dependencies:
    description: 'Workspace to source where dependencies are'
    required: false
    default: ''

runs:
  using: composite
  steps:

    - name: Build workspace with colcon
      shell: pwsh
      run: |

        "::group::Run tests using colcon"

        if ([string]::IsNullOrEmpty(${{ inputs.file_result }})) {
          ${{ inputs.workspace_dependencies }}/setup.ps1
        }

        cd ${{ inputs.workspace }}

        colcon test `
          ${{ inputs.colcon_test_args_default }} `
          ${{ inputs.colcon_test_args }} `
          --ctest-args `
            ${{ inputs.ctest_args_default }} ${{ inputs.ctest_args }}

        "::endgroup::"
