name: 'flakiness_report'
description: 'Generate a flakiness report from test results and historical data'

inputs:
  junit_reports_dir:
    description: 'Path to dir with new jUnit reports'
    required: true

  junit_archive_artifact:
    description: 'Name of the artifact containing the historical data'
    required: true

  print_report:
    description: 'Whether to print the report (Default: True)'
    required: false
    default: 'True'

  window_size:
    description: 'Number of days to consider for the flakiness report'
    required: false
    default: '30'

  fail_on_flaky_tests:
    description: 'Whether to fail the workflow if there are flaky tests'
    required: false
    default: 'True'

  github_token:
    description: 'GitHub token'
    required: true

runs:
  using: composite
  steps:
    - name: Install python dependencies
      id: install_python_dependencies
      uses: eProsima/eProsima-CI/ubuntu/install_python_packages@v0
      with:
        packages: lxml junitparser pandas

    - name: Download jUnit archive
      id: download_junit_archive
      uses: eProsima/eProsima-CI/external/action-download-artifact@v0
      with:
        name: ${{ inputs.junit_archive_artifact }}
        path: junit_archive
        github_token: ${{ inputs.github_token }}
        workflow_conclusion: completed
        if_no_artifact_found: ignore

    - name: Flakiness Report
      id: flakiness_report
      shell: bash
      run: |
        WINDOW_SIZE_OPTION="--window-size ${{ inputs.window_size }}"

        MD_FILE_OPTION=""
        if [[ "${{ inputs.print_report }}" == "True" ]]
        then
          MD_FILE_OPTION="--markdown-file $GITHUB_STEP_SUMMARY"
        fi

        mkdir -p junit_archive
        cp ${{ inputs.junit_reports_dir }}/*.xml junit_archive

        EXIT_CODE=0
        python3 ${{ github.action_path }}/../../resources/flakiness_report.py \
          --junit-archive junit_archive \
          ${WINDOW_SIZE_OPTION} \
          --delete-old-files \
          --json-file flaky_tests.json \
          ${MD_FILE_OPTION}

        EXIT_CODE=$((${EXIT_CODE} + $?))

        if [[ "${{ inputs.fail_on_flaky_tests }}" != "True" ]]
        then
          EXIT_CODE=0
        fi

        exit ${EXIT_CODE}

    - name: Upload jUnit archive
      id: upload_junit_archive
      if: always()
      uses: eProsima/eProsima-CI/external/upload-artifact@v0
      with:
        name: ${{ inputs.junit_archive_artifact }}
        path: junit_archive

    - name: Upload JSON report
      id: upload_json_report
      if: always()
      uses: eProsima/eProsima-CI/external/upload-artifact@v0
      with:
        name: ${{ inputs.junit_archive_artifact }}_json
        path: flaky_tests.json
