name: fetch_dev_utils_manual
description: Download eProsima/dev-utils setting the specific version of each repository

inputs:

  dev_utils_branch:
    description: >
      Branch, tag or commit of eProsima/dev-utils repository.
      Check available branches in https://github.com/eProsima/dev-utils.
    required: false
    default: master

  destination_workspace:
    description: 'Workspace where the repositories are downloaded'
    required: false
    default: '${{ github.workspace }}'

runs:
  using: composite
  steps:

    - name: fetch_dev_utils_manual
      run: |

        echo "::group::Manually clone dev-utils repository"

        echo "Downloading following dependencies:"
        echo "  - dev-utils: ${{ inputs.dev_utils_branch }}"

        mkdir -p ${{ inputs.destination_workspace }}
        cd ${{ inputs.destination_workspace }}
        git clone --branch ${{ inputs.dev_utils_branch }} https://github.com/eProsima/dev-utils.git

        echo "::endgroup::"

      shell: bash
