name: 'setup_python_venv'
description: 'Setup a Python virtual environment and add it to the PATH'

inputs:

  path:
    description: 'Path to virtual environment'
    required: false
    default: '.venv'

  activate_global:
    description: 'Activate the virtual environment globally'
    required: false
    default: true

runs:
  using: composite
  steps:

    - name: 'setup_python_venv'
      run: |

        echo "::group::Setup Python virtual environment"

        if [ -d "${{ inputs.path }}" ] && [ -f "${{ inputs.path }}/bin/activate" ]; then
          echo "Virtual environment exists."
        else
          # Create a virtual environment
          python3 -m venv ${{ inputs.path }}
          source ${{ inputs.path }}/bin/activate

          if [ "${{ inputs.activate_global }}" = "true" ]; then
            echo PATH=$PATH >> $GITHUB_ENV
          fi
        fi

        echo "::endgroup::"

      shell: bash
