# Execute makrdownlint MarkDown linter job from the same repo that calls this action.
#
# Runs on:
# - Ubuntu 20.04
# - Ubuntu 22.04
#
# Steps:
# - Checkout repository and fetch unshallow to be able to compare
# - Install packages required
# - Get the file names of those files that has changed between base and head branch
# - Execute makrdownlint over those files (only .md and README ones).
#
# Arguments:
# - linter_configuration_version : branch of cpp-style repo to get configuration from [master]
# - markdownlint_version : branch of markdownlint/markdownlint repo to download tool [v0.12.0]
# - file_grep_args : grep filer for file extensions [-e '\\.md' -e 'README']

name: markdown_linter
description: MarkDown Linter action to check Python modified files.

inputs:

  linter_configuration_version:
    description: 'Branch of eProsima/cpp-style'
    required: false
    default: master

  file_grep_args:
    description: 'Extensions of the files to check as markdown, as grep filter arguments.'
    required: false
    default: "-e '\\.md' -e 'README'"

runs:
  using: composite
  steps:

    - name: Sync repository
      uses: eProsima/eProsima-CI/external/checkout@feature/markdown-linter
      with:
        path: src

    - name: Fetch all branches and tags
      uses: eProsima/eProsima-CI/ubuntu/git_fetch_all@feature/markdown-linter
      with:
        workspace: src

    - name: Install markdownlint
      uses: eProsima/eProsima-CI/ubuntu/install_markdownlint@feature/markdown-linter

    - name: Fetch markdown linter config file
      uses: eProsima/eProsima-CI/ubuntu/get_file_from_repo@feature/markdown-linter
      with:
        source_repository_branch: ${{ inputs.linter_configuration_version }}
        source_repository: eProsima/cpp-style
        file_name: markdownlint_linter.rb
        file_result: markdownlint_linter.rb

    - name: Get Git difference
      id: GetGitDifference
      uses: eProsima/eProsima-CI/ubuntu/get_git_diff_files@feature/markdown-linter
      with:
        result_env_var:
          MODIFIED_FILES
        head_ref:
          origin/${GITHUB_HEAD_REF}
        base_ref:
          origin/${GITHUB_BASE_REF}
        grep_args:
          ${{ inputs.file_grep_args }}
        workspace:
          src

    - name: Check difference is not empty
      run: |
        cd src
        if [[ -z "${MODIFIED_FILES}" ]]
        then
          touch __empty.md
          echo "MODIFIED_FILES=__empty.md" >> $GITHUB_ENV
        fi
        echo "Files to check: ${MODIFIED_FILES}"
      shell: bash

    # TODO remove
    # This file is required due to a bug in markdownlint that do not allow to use a config file
    - name: Add config path file
      run: |
        cd src
        echo "style '../markdownlint_linter.rb'" > .mdlrc
        ls
        cat .mdlrc
        cat ../markdownlint_linter.rb
      shell: bash

    - name: Check style
      run: |
        cd src

        echo "################################################################################################"
        echo "################################### MARKDOWN LINTER RESULTS ####################################"

        mdl ${MODIFIED_FILES}

        # When bug is fixed, uncomment this
        # mdl --config ../markdownlint_linter.rb ${MODIFIED_FILES}

        echo "############################### MARKDOWN LINTER CHECK SUCCESSFUL ###############################"
        echo "################################################################################################"

      shell: bash
