name: 'install_apt_packages'
description: 'Install apt packages'

inputs:
  custom_packages:
    description: 'Custom packages to install using apt'
    required: false
    default: 'curl grep python3 python3-pip software-properties-common wget'

runs:
  using: composite
  steps:

    - name: install_apt_packages

      run: |
        echo "::group::Install apt packages"
        sudo apt update && sudo apt -y install \
          ${{ inputs.custom_packages }}
        echo "::endgroup::"

      shell: bash
