name: 'install_apt_packages'
description: 'Install generic and required apt packages'
inputs:
  custom_packages:
    description: 'Custom packages to install using apt'
    required: false
    default: ''
runs:
  using: composite
  steps:
    - id: install-apt-packages
      run: |
        sudo apt update && sudo apt -y install \
          curl \
          grep \
          python3 \
          python3-pip \
          software-properties-common \
          wget \
          ${{ inputs.custom_packages }}
      shell: bash
