name: 'install_apt_packages'
description: 'Install apt packages'

inputs:

  packages:
    description: 'Custom packages to install using apt'
    required: true

  update:
    description: 'Update apt'
    required: false
    default: 1

  upgrade:
    description: 'Upgrade already installed apt packages'
    required: false
    default: 0

runs:
  using: composite
  steps:

    - name: install_apt_packages
      run: |

        echo "::group::Install apt packages ${{ inputs.custom_packages }}"

        # Update apt repos
        if ${{ inputs.update }} ; then
          sudo apt update
        fi

        # Install custom packages
        sudo apt -y install \
          ${{ inputs.packages }}

        # Upgrade apt repos
        if ${{ inputs.upgrade }} ; then
          sudo apt upgrade
        fi

        echo "::endgroup::"

      shell: bash
