name: 'install_fastdds_dependencies'
description: 'Install Fast DDS dependencies in ubuntu'

inputs:
  cmake_build_type:
    description: 'Specify the build type on single-configuration generators'
    required: true
    default: 'Release'

runs:
  using: composite
  steps:

    - name: Install colcon
      uses: eProsima/eProsima-CI/windows/install_colcon@main

    - name: Install GTest
      uses: eProsima/eProsima-CI/windows/install_gtest@main
      with:
        cmake_build_type: ${{ inputs.cmake_build_type }}

    - name: Install Open SSL
      uses: eProsima/eProsima-CI/windows/install_openssl@main
