name: 'vcs_import'
description: 'Import some repositories and their versions from a yaml file'

inputs:

  vcs_repos_file:
    description: '.repos file to import repositories'
    required: true

  destination_workspace:
    description: 'Workspace to source where dependencies are'
    required: false
    default: '${{ github.workspace }}'

runs:
  using: composite
  steps:

    - name: Run in ubuntu
      uses: eProsima/eProsima-CI/ubuntu/vcs_import@feature/annapurna-workflows
      if: runner.os == 'Linux'
      with:
        vcs_repos_file: ${{ inputs.vcs_repos_file }}
        destination_workspace: ${{ inputs.destination_workspace }}

    - name: Run in windows
      uses: eProsima/eProsima-CI/windows/vcs_import@feature/annapurna-workflows
      if: runner.os == 'Windows'
      with:
        vcs_repos_file: ${{ inputs.vcs_repos_file }}
        destination_workspace: ${{ inputs.destination_workspace }}
