name: install_uncrustify

runs:
  using: composite
  steps:

    - name: Install uncrustify
      uses: eProsima/eProsima-CI/ubuntu/install_apt_packages@v0.3.0
      with:
        packages: uncrustify
