name: 'generate_dependency'
description: 'TODO'

inputs:

  workflow_source:
    description: 'Name of the workflow to look for'
    required: true

  workflow_source_repository:
    description: 'Name of the repository to look for the job id [this repository]'
    required: false
    default: '$GITHUB_REPOSITORY'

  id_job_result:
    description: 'Name of the env variable to store the job id'
    required: false
    default: 'job_id'

  job_status:
    description: 'Workspace to source where dependencies are'
    required: false
    default: 'completed'

runs:
  using: composite
  steps:

    - name: Get build eProsima dependencies Job Id
      run: |

        echo "::group::Get Id from workflow ${{ inputs.workflow_source }}"

        echo "$GITHUB_API_URL/repos/${{ inputs.workflow_source_repository }}/actions/workflows/${{ inputs.workflow_source }}/runs"
        export JOB_ID=$(curl -sL $GITHUB_API_URL/repos/${{ inputs.workflow_source_repository }}/actions/workflows/${{ inputs.workflow_source }}/runs | \
          jq '.workflow_runs[] | select(.status == "${{ inputs.job_status }}") | .id' | \
          head -n 1)
        echo "Job Id: ${JOB_ID}"
        echo "${{ inputs.id_job_result }}=${JOB_ID}" >> $GITHUB_ENV

        echo "::endgroup::"

      shell: bash
