name: 'install_asio'

runs:
  using: composite
  steps:

    - name: Install in ubuntu
      uses: eProsima/eProsima-CI/ubuntu/install_apt_packages@hotfix/setup-python-venv
      with:
        packages: libasio-dev
