name: 'fgt_platform'
description: 'Set some env var with information about the platform where the action is executed'

inputs:

  ubuntu_version_env:
    description: 'Environment Variable to store ubuntu version'
    required: false
    default: 'EPROSIMA_UBUNTU_VERSION'

runs:
  using: composite
  steps:

    - name: Set Ubuntu version
      run: |

        echo "::group::Set ubuntu version in evn var ${{ inputs.ubuntu_version_env }}"

        if [[ -z ${${{ inputs.ubuntu_version_env }}} ]]; then
          export EPROSIMA_UBUNTU_VERSION_=$(lsb_release -d | cut -f2)
          echo "${{ inputs.ubuntu_version_env }}=${EPROSIMA_UBUNTU_VERSION_}" >> $GITHUB_ENV
          echo "Ubuntu version: ${{ inputs.ubuntu_version_env }} = ${EPROSIMA_UBUNTU_VERSION_}"
        fi

        echo "::endgroup::"

      shell: bash
