name: 'clang_tidy_check'
description: 'Run clang tidy check.'

inputs:

  build_directory_arg:
    description: 'Directory where builds are'
    required: false
    default: 'build'

  packages_names:
    description: 'If set, it will look for these packages inside directory <build_directory_arg>'
    required: false
    default: ''

  result_file_name:
    description: 'Name of file to save result (advisable to use absolute path).'
    required: false
    default: 'clang_results.yml'

runs:
  using: composite
  steps:

    - name: Run clang tidy check
      run: |

        echo "::group::Run clang tidy"

        if [[ ! -z "${{ inputs.packages_names }}" ]]; then
          mkdir -p ${{ inputs.build_directory_arg }}/_all
          cp --recursive ${{ inputs.build_directory_arg }}/${{ inputs.packages_names }} ${{ inputs.build_directory_arg }}/_all
          cd ${{ inputs.build_directory_arg }}/_all
        else
          cd ${{ inputs.build_directory_arg }}
        fi

        run-clang-tidy -header-filter='.*' -checks='clang-analyzer-cplusplus' -quiet 2> ${{ inputs.result_file_name }}

        echo "::endgroup::"

      shell: bash
