name: 'clang_tidy_check'
description: 'Run clang tidy check.'

inputs:

  build_directory:
    description: 'Directory where builds are'
    required: false
    default: 'build'

  packages_names:
    description: 'If set, it will look for these packages inside directory <build_directory>'
    required: false
    default: ''

  result_file_name:
    description: 'Name of file to save result (advisable to use absolute path).'
    required: false
    default: 'clang_results.yml'

runs:
  using: composite
  steps:

    - name: Run clang tidy check
      run: |

        echo "::group::Run clang tidy"

        if [[ ! -z "${{ inputs.packages_names }}" ]]; then
          mkdir -p ${{ inputs.build_directory }}/_all
          cp --recursive ${{ inputs.build_directory }}/${{ inputs.packages_names }} ${{ inputs.build_directory }}/_all
          cd ${{ inputs.build_directory }}/_all
        else
          cd ${{ inputs.build_directory }}
        fi

        run-clang-tidy -header-filter='.*' -quiet > ${{ inputs.result_file_name }} 2>&1

        echo "Clang results:"
        cat ${{ inputs.result_file_name }}

        tail -f ${{ inputs.result_file_name }} | grep -r 'warning|error'
        if [ $? -eq 0 ]; then
          echo "No errors or warnings"
        else
          return 1
        fi

        echo "::endgroup::"

      shell: bash
