# TODO

name: build_ddspipe

on:

  workflow_dispatch:

    inputs:

      built_configuration_branch:
        description: 'Branch or tag of eProsima-CI repository to get .repos and colcon.meta from that will be executed'
        required: false
        default: 'main'

      artifacts_name_postfix:
        description: 'Addition to artifacts name creation (use non default postfix when creating artifacts with specific arguments).'
        required: false
        default: '_manual'

  schedule:

    # Every night at 02:00
    - cron: '0 2 * * *'

env:
  default_configuration_branch: 'main'
  default_artifact_postfix: '_nightly'

jobs:

  build_ddspipe:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        cmake_build_type:
          - Release
          - Debug
        os:
          - ubuntu-20.04
          - ubuntu-22.04
          - windows-2019
          - windows-2022

    # Windows env variables
    env:
      CXXFLAGS: /MP
      OPENSSL64_ROOT: "C:/Program Files/OpenSSL-Win64"

    steps:

      - name: Sync this repository
        uses: actions/checkout@v3
        with:
          path: src/eprosima-CI

      - name: Install yaml cpp dependency
        uses: jparisu/eProsima-CI/multiplatform/install_yamlcpp@main
        with:
          cmake_build_type: ${{ matrix.cmake_build_type }}

      - name: Get dev_utils artifact
        uses: jparisu/eProsima-CI/multiplatform/download_dependency@main
        with:
          artifact_name: built_dev_utils_${{ matrix.os }}_${{ matrix.cmake_build_type }}${{ inputs.artifacts_name_postfix || env.default_artifact_postfix }}
          workflow_source: build_dev_utils.yml
          target_workspace: install
          workflow_source_repository: ${{ github.repository }}
          secret_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get colcon.meta and .repos files to build artifact
        uses: jparisu/eProsima-CI/multiplatform/get_configurations_from_repo@main
        with:
          source_repository_branch: ${{ inputs.built_configuration_branch || env.default_configuration_branch }}
          colcon_meta_file_path: .github/workflows/configurations/metas/${{ matrix.os }}/colcon.meta
          repos_file_path: .github/workflows/configurations/ddspipe/dependencies.repos

      - name: Build and generate artifact
        uses: jparisu/eProsima-CI/multiplatform/generate_dependency@main
        with:
          vcs_repos_file: ${{ github.workspace }}/dependencies.repos
          artifact_name: built_ddspipe_${{ matrix.os }}_${{ matrix.cmake_build_type }}${{ inputs.artifacts_name_postfix || env.default_artifact_postfix }}
          colcon_meta_file: ${{ github.workspace }}/colcon.meta
          workspace: ${{ github.workspace }}
          workspace_dependencies: install
          cmake_build_type: ${{ matrix.cmake_build_type }}
