# TODO

name: build_ddspipe

on:

  workflow_dispatch:

    inputs:

      built_configuration_branch:
        description: 'Branch or tag of eProsima-CI repository to get .repos and colcon.meta from that will be executed'
        required: false
        default: 'main'

      artifacts_name_postfix:
        description: 'Addition to artifacts name creation (use non default postfix when creating artifacts with specific arguments).'
        required: false
        default: '_manual'

  schedule:

    # Every night at 02:00
    - cron: '0 2 * * *'

env:
  default_configuration_branch: 'main'
  default_artifact_postfix: '_nightly'

jobs:

  build_ddspipe:

    runs-on: ${{ matrix.ubuntu-version }}
    strategy:
      fail-fast: false
      matrix:
        ubuntu-version:
          - 'ubuntu-20.04'
          - 'ubuntu-22.04'

    steps:

      - name: Sync this repository
        uses: actions/checkout@v3
        with:
          path: src/eprosima-CI

      - name: Install yaml cpp dependency
        uses: jparisu/eProsima-CI/ubuntu/install_yamlcpp@feature/windows-support

      - name: Get dev_utils artifact
        uses: jparisu/eProsima-CI/multiplatform/download_dependency@feature/windows-support
        with:
          artifact_name: built_dev_utils_${{ matrix.ubuntu-version }}${{ inputs.artifacts_name_postfix || env.default_artifact_postfix }}
          workflow_source: build_dev_utils.yml
          target_workspace: install
          workflow_source_repository: jparisu/eProsima-CI
          # TODO: check why GITHUB_REPOSITORY is not correctly being set

      - name: Get colcon.meta and .repos files to build artifact
        uses: jparisu/eProsima-CI/multiplatform/get_configurations_from_repo@feature/windows-support
        with:
          source_repository_branch: ${{ inputs.built_configuration_branch || env.default_configuration_branch }}
          colcon_meta_file_path: .github/workflows/configurations/ddspipe/colcon.meta
          repos_file_path: .github/workflows/configurations/ddspipe/dependencies.repos

      - name: Build and generate artifact
        uses: jparisu/eProsima-CI/multiplatform/generate_dependency@feature/windows-support
        with:
          vcs_repos_file: dependencies.repos
          artifact_name: built_ddspipe_${{ matrix.ubuntu-version }}${{ inputs.artifacts_name_postfix || env.default_artifact_postfix }}
          colcon_meta_file: colcon.meta
          workspace: ${{ github.workspace }}
          workspace_dependencies: install
