# TODO

name: build_dev_utils

on:

  workflow_dispatch:

    inputs:

      built_configuration_branch:
        description: 'Branch or tag of eProsima-CI repository to get .repos and colcon.meta from that will be executed'
        required: false
        default: 'main'

      artifacts_name_postfix:
        description: 'Addition to artifacts name creation (use non default postfix when creating artifacts with specific arguments).'
        required: false
        default: '_manual'

  schedule:

    # Every night at 01:00
    - cron: '0 1 * * *'

env:
  default_configuration_branch: 'main'
  default_artifact_postfix: '_nightly'

jobs:

  build_dev_utils:

    runs-on: ${{ matrix.ubuntu-version }}
    strategy:
      fail-fast: false
      matrix:
        ubuntu-version:
          - 'ubuntu-20.04'
          - 'ubuntu-22.04'

    steps:

      - name: Sync this repository
        uses: actions/checkout@v3
        with:
          path: src/eprosima-CI

      - name: Get fastdds artifact
        uses: jparisu/eProsima-CI/ubuntu/download_dependency@main
        with:
          artifact_name: built_fastdds_${{ matrix.ubuntu-version }}${{ inputs.artifacts_name_postfix || env.default_artifact_postfix }}
          workflow_source: build_fastdds.yml
          target_workspace: dependencies/install
          workflow_source_repository: jparisu/eProsima-CI
          # TODO: check why GITHUB_REPOSITORY is not correctly being set

      - name: Get colcon.meta and .repos files to build artifact
        uses: jparisu/eProsima-CI/ubuntu/get_configurations_from_repo@main
        with:
          source_repository_branch: ${{ inputs.built_configuration_branch || env.default_configuration_branch }}
          colcon_meta_file_path: .github/workflows/configurations/dev_utils/colcon.meta
          repos_file_path: .github/workflows/configurations/dev_utils/dependencies.repos

      - name: Build and generate artifact
        uses: jparisu/eProsima-CI/ubuntu/generate_dependency@main
        with:
          vcs_repos_file: dependencies.repos
          artifact_name: built_dev_utils_${{ matrix.ubuntu-version }}${{ inputs.artifacts_name_postfix || env.default_artifact_postfix }}
          colcon_meta_file: colcon.meta
          workspace_dependencies: dependencies/install
