name: pr_test

on:
  workflow_call:

jobs:

  dummy:
    runs-on: ubuntu-22.04
    steps:
      - name: Do nothing yet
        shell: bash
        run: |
          echo "github.job: ${{ github.job }}"
          echo "github.jobs[github.job]: ${{ github.jobs[github.job] }}"
          echo "github.jobs[github.job].name: ${{ github.jobs[github.job].name }}"
          echo "github.jobs[github.job].id: ${{ github.jobs[github.job].id }}"
          echo "github.workflow-github.job: ${{ github.workflow }}-${{ github.job }}"
