name: pr_test

on:
  workflow_dispatch:
  pull_request:

jobs:

  version-update:
    runs-on: ubuntu-22.04
    steps:

      - name: Check wether the versions.md file have been updated
        uses: eProsima/eProsima-CI/ubuntu/check_version_update@feature/versions-update

  testing:
    runs-on: ubuntu-22.04
    steps:

      - name: Sync repository
        uses: eProsima/eProsima-CI/external/checkout@feature/versions-update
        with:
          path: ${{ github.workspace }}

      - name: Fetch all branches and tags
        uses: eProsima/eProsima-CI/ubuntu/git_fetch_all@feature/versions-update
        with:
          workspace: ${{ github.workspace }}

      - name: Test outputs
        id: test1
        shell: bash
        run: |

          echo "$GITHUB_OUTPUT"
          cat $GITHUB_OUTPUT
          echo "test1-output=false" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

      - name: Test outputs reception
        shell: bash
        run: |

          echo "$GITHUB_OUTPUT"
          cat $GITHUB_OUTPUT
          echo "${{ steps.test1.outputs.test1-output }}"

      - name: Get diff file of version file
        id: diff
        uses: eProsima/eProsima-CI/ubuntu/git_diff@feature/versions-update
        with:
          file-path: ${{ github.workspace }}/${{ inputs.version-file-path }}


      - name: Check if file change
        shell: bash
        run: |

          cat $GITHUB_OUTPUT

          if [[ "${{ steps.diff.outputs.have-changes }}" != "true" ]]; then
            echo "Version file ${{ inputs.version-file-path }} has not been updated"
            echo "T.T"
            exit 1
          else
            echo "Version file ${{ inputs.version-file-path }} updated."
            echo "HURRAY! ^.^"
          fi


  testing2:
    runs-on: ubuntu-22.04
    outputs:
      out1: ${{ steps.action1.outputs.out }}
      out2: ${{ steps.action2.outputs.out }}
    steps:

      - name: Sync repository
        uses: eProsima/eProsima-CI/external/checkout@feature/versions-update
        with:
          path: src

      - name: Run some action with output
        id: action1
        uses: ./src/.github/actions/action_with_output

      - name: Run some shell with output
        id: action2
        shell: bash
        run: echo "out=true" >> $GITHUB_OUTPUT

      - name: Get output 1
        shell: bash
        run: echo "OUTPUT ${{ steps.action1.outputs.out }}"

      - name: Get output 2
        if: ${{ steps.action1.outputs.out }} == true
        shell: bash
        run: echo "OUTPUT true"

      - name: Get output 3
        if: ${{ steps.action1.outputs.out }} != true
        shell: bash
        run: echo "OUTPUT diff true"

      - name: Get output 4
        shell: bash
        run: echo "OUTPUT ${{ steps.action2.outputs.out }}"

  testing3:
    runs-on: ubuntu-22.04
    needs: [testing2]
    steps:

      - name: Get output from other job
        shell: bash
        run: echo "OUTPUT ${{ steps.testing2.outputs.out1 }}"

      - name: Get output from other job
        shell: bash
        run: echo "OUTPUT ${{ steps.testing2.outputs.out2 }}"
