name: pr_test

on:
  workflow_dispatch:
  pull_request:

jobs:

  version-update:
    runs-on: ubuntu-22.04
    steps:

      - name: Check wether the versions.md file have been updated
        uses: eProsima/eProsima-CI/ubuntu/check_version_update@feature/versions-update

  testing:
    runs-on: ubuntu-22.04
    steps:

      - name: Sync repository
        uses: eProsima/eProsima-CI/external/checkout@feature/versions-update
        with:
          path: ${{ github.workspace }}

      - name: Fetch all branches and tags
        uses: eProsima/eProsima-CI/ubuntu/git_fetch_all@feature/versions-update
        with:
          workspace: ${{ github.workspace }}

      - name: Test outputs
        id: test1
        shell: bash
        run: |

          echo "$GITHUB_OUTPUT"
          cat $GITHUB_OUTPUT
          echo "test1-output=false" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

      - name: Test outputs reception
        shell: bash
        run: |

          echo "$GITHUB_OUTPUT"
          cat $GITHUB_OUTPUT
          echo "${{ steps.test1.outputs.test1-output }}"

      - name: Get diff file of version file
        id: diff
        uses: eProsima/eProsima-CI/ubuntu/git_diff@feature/versions-update
        with:
          file-path: ${{ github.workspace }}/${{ inputs.version-file-path }}


      - name: Check if file change
        shell: bash
        run: |

          cat $GITHUB_OUTPUT

          if [[ "${{ steps.diff.outputs.have-changes }}" != "true" ]]; then
            echo "Version file ${{ inputs.version-file-path }} has not been updated"
            echo "T.T"
            exit 1
          else
            echo "Version file ${{ inputs.version-file-path }} updated."
            echo "HURRAY! ^.^"
          fi
