name: pr_test
description: Check Pull Request

on:
  workflow_dispatch:
  pull_request:

jobs:

  version-update:
    runs-on: ubuntu-22.04
    steps:
      - name: Check wether the versions.md file have been updated
        uses: eProsima/eProsima-CI/ubuntu/check_version_update@main
