
name: test_actions

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *'

jobs:

  windows-build-test:
    runs-on: ${{ matrix.windows-version }}
    strategy:
      fail-fast: false
      matrix:
        cmake-config:
          - 'Release'
          - 'Debug'
        windows-version:
          - 'windows-2019'
          - 'windows-2022'
    env:
      CXXFLAGS: /MP
      OPENSSL64_ROOT: "C:/Program Files/OpenSSL-Win64"

    steps:

      - name: Install fastdds dependencies
        uses: jparisu/eProsima-CI/multiplatform/install_fast_dependencies@feature/windows-support

      - name: Install yaml cpp
        uses: jparisu/eProsima-CI/windows/install_yamlcpp@feature/windows-support

      - name: Get file from repo
        uses: jparisu/eProsima-CI/multiplatform/get_file_from_repo@feature/windows-support
        with:
          file_name: LICENSE
          file_result: license
