
name: test_actions

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *'

jobs:

  windows-build-test:
    runs-on: ${{ matrix.windows-version }}
    strategy:
      fail-fast: false
      matrix:
        cmake-config:
          - 'Release'
          - 'Debug'
        windows-version:
          - 'windows-2019'
          - 'windows-2022'
    env:
      CXXFLAGS: /MP
      OPENSSL64_ROOT: "C:/Program Files/OpenSSL-Win64"

    steps:

      - name: Sync this repository
        uses: actions/checkout@v3
        with:
          path: src/eprosima-CI

      - name: Get colcon.meta and .repos files to build fastdds
        uses: jparisu/eProsima-CI/multiplatform/get_configurations_from_repo@feature/windows-support
        with:
          source_repository_branch: feature/windows-support
          colcon_meta_file_path: .github/workflows/configurations/fastdds/colcon.meta
          repos_file_path: .github/workflows/configurations/fastdds/dependencies.repos

      - name: dependencies
        uses: jparisu/eProsima-CI/multiplatform/install_fast_dependencies@feature/windows-support

      - name: Build Fast DDS and generate artifact
        uses: jparisu/eProsima-CI/multiplatform/generate_dependency@feature/windows-support
        with:
          vcs_repos_file: ${{ github.workspace }}\dependencies.repos
          artifact_name: built_fastdds_${{ matrix.windows-version }}
          colcon_meta_file: ${{ github.workspace }}\colcon.meta
          cmake-config: ${{ matrix.cmake-config }}
