name: 'junit_summary'
description: 'Generate a summary from a jUnit report. This summary shows in the workflow summary page. Exit code is number of failed tests.'

inputs:
  junit_reports_dir:
    description: 'Path to directory containing XML files with the jUnit reports'
    required: true

  print_summary:
    description: 'Whether to print the summary (Default: True)'
    required: false
    default: 'True'

  show_failed:
    description: 'Whether to show the list of failed tests (Default: True)'
    required: false
    default: 'True'

  show_disabled:
    description: 'Whether to show the list of disabled tests (Default: False)'
    required: false
    default: 'False'

  show_skipped:
    description: 'Whether to show the list of skipped tests (Default: False)'
    required: false
    default: 'False'

  flaky_json_report:
    description: 'Path to a JSON file with the flaky tests report'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: jUnit Summary
      id: junit_summary
      shell: bash
      run: |
        OUTPUT_FILE_OPTION="--output-file $GITHUB_STEP_SUMMARY"

        PRINT_SUMMARY_OPTION=""
        if [[ "${{ inputs.print_summary }}" == "True" ]]
        then
          PRINT_SUMMARY_OPTION="--print-summary"
        fi

        SHOW_FAILED_OPTION=""
        if [[ "${{ inputs.show_failed }}" == "True" ]]
        then
          SHOW_FAILED_OPTION="--show-failed"
        fi

        SHOW_DISABLED_OPTION=""
        if [[ "${{ inputs.show_disabled }}" == "True" ]]
        then
          SHOW_DISABLED_OPTION="--show-disabled"
        fi

        SHOW_SKIPPED_OPTION=""
        if [[ "${{ inputs.show_skipped }}" == "True" ]]
        then
          SHOW_SKIPPED_OPTION="--show-skipped"
        fi

        FLAKY_JSON_REPORT_OPTION=""
        if [[ -f "${{ inputs.flaky_json_report }}" ]]
        then
          FLAKY_JSON_REPORT_OPTION="--flaky-json-report ${{ inputs.flaky_json_report }}"
        fi

        EXIT_CODE=0
        for JUNIT_REPORT in ${{ inputs.junit_reports_dir }}/*.xml
        do
          python3 ${{ github.action_path }}/../../resources/junit_summary.py \
            --junit-report ${JUNIT_REPORT} \
            ${OUTPUT_FILE_OPTION} \
            ${PRINT_SUMMARY_OPTION} \
            ${SHOW_FAILED_OPTION} \
            ${SHOW_DISABLED_OPTION} \
            ${SHOW_SKIPPED_OPTION} \
            ${FLAKY_JSON_REPORT_OPTION}

          EXIT_CODE=$((${EXIT_CODE} + $?))
        done

        exit ${EXIT_CODE}
